### ISSUE TITLE
White bar around the open button in VesselView

### ISSUE THREAD

**Issue by vovythevov** [KitwareMedical/VesselView#113]
I am not sure that I am using the correct style. But I get this:

![bug1](https://cloud.githubusercontent.com/assets/426898/8629915/0408a206-272e-11e5-9bff-bec09d4741d7.PNG)

I expect that it's simply a question of changing the opacity of the rectangle in QML.

**Comment by vovythevov** [comment]
Coincidentally, the open button turns grey after the first time it has been clicked.

**Comment by aylward** [comment]
Two good catches.  Thanks!

S

**Comment by aylward** [comment]
To be confirmed as fixed by Sumedha

**Comment by sumedhasingla** [comment]
Verified on the latest version. 
![issue 113](https://cloud.githubusercontent.com/assets/13970739/9670031/6bcf4b2e-5258-11e5-964f-2a44469f1383.JPG)
