### ISSUE TITLE
Create hierarchy of tasks in launcher

### ISSUE THREAD

**Issue by aylward** [KitwareMedical/VesselView#122]
1) Add Segment Vessels button on the left side.
Remove Interactive Vessel Segmentation and Automatic Vessel Segmentation from left side.

In Segment Vessels panel, have two buttons above recent files.
- Interactive  and Automatic

2) Similarly, Add a Utilities button on the left side, below Organ Segmentation
Remove Convert Vessel Files from left side

In Utilities panel, have a button for Convert Vessel Files, Crop Image, ...

**Comment by sumedhasingla** [comment]
To provide further options under one task, I have created a horizontal task list. The Utilities panel also have a button for Crop Volume. The description of task is yet to be added.

**Comment by sumedhasingla** [comment]
The issue is fixed in pull request: #132
