### ISSUE TITLE
Recent files list moves down the launcher display

### ISSUE THREAD

**Issue by aylward** [KitwareMedical/VesselView#124]
Recent files on the first panel (View) is correctly positioned, but it moves lower for subsequent panels.

**Comment by sumedhasingla** [comment]
Made changes in the list view properties. Can you please verify if it fixed the problem.

**Comment by sumedhasingla** [comment]
Fixed in Pull request #132 
BUG: Fixed the relative position of Recent File text.
#133 
Bug: Fixed an issue with "Recent Files" textbox.
