### ISSUE TITLE
Make sure the PDF segmenter works correctly

### ISSUE THREAD

**Issue by vovythevov** [KitwareMedical/VesselView#15]

**Comment by vovythevov** [comment]
i.e. adding a test

**Comment by vovythevov** [comment]
##How to run a test:
Use the command ctest (part of CMake package). For more info on ctest: http://www.vtk.org/Wiki/CMake/Testing_With_CTest. In particular, you might want to use ctest -VV -R NameOfTest  

### Running in VesselView
Tests are built in Applications/App. So to run a test, you need to be in that folder. That would be something like: .../Work/VesselView-build/Slicer-build/Slicer-build/Applications/App

### How to debug a test in VesselView
Test either fail or pass but they don't show why they fail. Here is how to debug them.
If you run the test with the verbose option (-VV) you can see all it really does is calling vesselview with some arguments. You can use this command line to run the test yourself and have all the debugging information (which isn't displayed otherwise).
An example of that would be using the command line: 
W:\V\S-build\Slicer-build\VesselView.exe "--no-splash" "--ignore-slicerrc" "--python-code" "import slicer.testing; slicer.testing.runUnitTest(['W:/V/S-build/Slicer-build/Applications/App/TestingPython', 'W:/Prometheus/P_srcs/Applications/App/Testing/Python'], 'WelcomeModuleTests')"
-> Note the missing "--testing" arguments

**Comment by jcfr** [comment]
Considering that (1) the PDF Segmenter has been updated in latest version of TubeTK and (2) this issue does not describe how to reproduce the problem, I am closing.
