### ISSUE TITLE
Add display tabs option

### ISSUE THREAD

**Issue by vovythevov** [KitwareMedical/VesselView#36]
3 steps, option for:
 - Slices
 - 3D (called Tubes)
 - MIP -> Implementation to see

**Comment by vovythevov** [comment]
See https://github.com/Slicer/Slicer/blob/master/Base/QTGUI/qSlicerLayoutManager.h
and https://github.com/Slicer/Slicer/blob/master/Base/Python/slicer/util.py

**Comment by matthieuheitz** [comment]
Note to self: my previous changes for that issue are on stash, 1st position, in my local VV folder.

**Comment by matthieuheitz** [comment]
After meeting with Stephen, we decided to place a pull-down menu at the bottom of the panel with the following options:
- Red Slice
- Yellow Slice
- Green Slice
- 3D View
- Quad View
- MIP

What do you think ?

**Comment by matthieuheitz** [comment]
After having edited the.ui file, QtCreator has modified some parts of the code that are not necessary to modify like:
```
-        <property name="nodeTypes">
+        <property name="nodeTypes" stdset="0">
          <stringlist>
           <string>vtkMRMLSpatialObjectsNode</string>
          </stringlist>
         </property>
-        <property name="showHidden">
+        <property name="showHidden" stdset="0">
          <bool>true</bool>
         </property>
-        <property name="baseName">
+        <property name="baseName" stdset="0">
          <string>Vessels</string>
         </property>
-        <property name="renameEnabled">
+        <property name="renameEnabled" stdset="0">
```
Should I clean that (remove the stdset="0") or leave it like this ?

**Comment by vovythevov** [comment]
For the options, I think it's reasonnable.
For Qt creator, yes it does that. Good practices are that you should only
commit parts of the code that you need and are related to what you are
doing. So tl;dr don't commit these :)

On Friday, February 6, 2015, Matthieu Heitz <notifications@github.com>
wrote:

> After having edited the.ui file, QtCreator has modified some parts of the
> code that are not necessary to modify like:
>
> -        <property name="nodeTypes">
> +        <property name="nodeTypes" stdset="0">
>           <stringlist>
>            <string>vtkMRMLSpatialObjectsNode</string>
>           </stringlist>
>          </property>
> -        <property name="showHidden">
> +        <property name="showHidden" stdset="0">
>           <bool>true</bool>
>          </property>
> -        <property name="baseName">
> +        <property name="baseName" stdset="0">
>           <string>Vessels</string>
>          </property>
> -        <property name="renameEnabled">
> +        <property name="renameEnabled" stdset="0">
>
> Should I clean that (remove the stdset="0") or leave it like this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KitwareMedical/VesselView/issues/36#issuecomment-73058370>
> .
>


-- 
Sent from Gmail Mobile

**Comment by matthieuheitz** [comment]
Okay great ! That's what I thought :)
It's going to be a pain ^^

**Comment by vovythevov** [comment]
Use git to do the work for you: i.e. Commit what you need and clean your
repo after (see git checkout -- )

On Friday, February 6, 2015, Matthieu Heitz <notifications@github.com>
wrote:

> Okay great ! That's what I thought :)
> It's going to be a pain ^^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KitwareMedical/VesselView/issues/36#issuecomment-73102948>
> .
>


-- 
Sent from Gmail Mobile

**Comment by matthieuheitz** [comment]
Yep, that's a good idea !

**Comment by matthieuheitz** [comment]
For the dropdown menu, I'm using a QComboBox.
Should I use a qMRMLNodeComboBox instead, or it doesn't matter ?
Visually, they look the same.

**Comment by vovythevov** [comment]
A qMRMLNodeComboBox is for nodes that are in the scene. It doesn't seem to
apply to you does it ?


On Tuesday, February 10, 2015, Matthieu Heitz <notifications@github.com>
wrote:

> For the dropdown menu, I'm using a QComboBox.
> Should I use a qMRMLNodeComboBox instead, or it doesn't matter ?
> Visually, they look the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KitwareMedical/VesselView/issues/36#issuecomment-73543166>
> .
>


-- 
Sent from Gmail Mobile

**Comment by matthieuheitz** [comment]
Oh okay, I understand the name now ! Thanks !
It doesn't apply.

**Comment by matthieuheitz** [comment]
Merged
