### ISSUE TITLE
Minimize the data probe by default

### ISSUE THREAD

**Issue by vovythevov** [KitwareMedical/VesselView#60]
This should probably be done in the welcome module.

**Comment by vovythevov** [comment]
I think it should be at the opening of vesselview. 
It seems counter intuitive for the user to have to pop it back up after opening each module.

I advise you to look in the defaultSetting.ini file (if I remember correctly). You can learn about what it does by looking at the main.cxx. (Also checkout Qt settings system).

**Comment by matthieuheitz** [comment]
Isn't adding: `slicer.util.findChildren(text='Data Probe')[0].collapsed = True` in the setup(self) of the WelcomeModule class sufficient (in Welcome.py) ? I've tested it, it works.
I don't really see where and how I could put that in the .ini file...

**Comment by vovythevov** [comment]
That could be the way to do it indeed.

On Thursday, February 5, 2015, Matthieu Heitz <notifications@github.com>
wrote:

> Isn't adding: slicer.util.findChildren(text='Data Probe')[0].collapsed =
> True in the setup(self) of the WelcomeModule class sufficient (in
> Welcome.py) ? I've tested it, it works.
> I don't really see where and how I could put that in the .ini file...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KitwareMedical/VesselView/issues/60#issuecomment-72962955>
> .
>


-- 
Sent from Gmail Mobile
