### ISSUE TITLE
Move the "-d" / "--develloper" option outside the main.cxx

### ISSUE THREAD

**Issue by vovythevov** [KitwareMedical/VesselView#63]
Since we now have our fork of slicer, it would be better to move this option in qSlicerCommandOptions
instead of having it as a hack in the main. 
Note that the hack for not loading the welcome module is probably still valid however.

**Comment by matthieuheitz** [comment]
For that, I modified the qSlicerCommandOptions, so I have to commit to KitwareMedical/Slicer, and then bump it here right ?
Do I need to do a fork of KitwareMedical/Slicer and make a pull-request, or can I just push on it directly ?

**Comment by vovythevov** [comment]
Yes. Let's do a pull request for now.

On Friday, February 6, 2015, Matthieu Heitz <notifications@github.com>
wrote:

> For that, I modified the qSlicerCommandOptions, so I have to commit to
> KitwareMedical/Slicer, and then bump it here right ?
> Do I need to do a fork of KitwareMedical/Slicer and make a pull-request,
> or can I just push on it directly ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KitwareMedical/VesselView/issues/63#issuecomment-73054147>
> .
>


-- 
Sent from Gmail Mobile
