### ISSUE TITLE
Tortuosity module

### ISSUE THREAD

**Issue by vovythevov** [KitwareMedical/VesselView#69]
[ ] Add Progress reporting (Started, Error, Completed)
[ ] Add a TableView that is populated by the tortuosity results.
 * It should have 4 columns: ID, DM, ICM, SOAM
 * A bottom row (or labels ?) with the avg, STD, Min and Max of each measure
 * Try to make it dockable. If not possible/too hard, make it so it can be poped open in a dialog window

**Comment by jcfr** [comment]
@sumedhasingla If this still applies, could you create an issue in TubeTK tracker and close this one ?

**Comment by sumedhasingla** [comment]
Created a new issue in TubeTK to track this issue. #660 (https://github.com/KitwareMedical/TubeTK/issues/660)

**Comment by jcfr** [comment]
Thanks
