### ISSUE TITLE
Tube Visibility toggle in Advanced Display->Tube tab toggles Line visibility instead of tube

### ISSUE THREAD

**Issue by matthieuheitz** [KitwareMedical/VesselView#87]
It might just be a signal/slot misconnection

**Comment by jcfr** [comment]
Similar widgets are also in Slicer. See https://github.com/Slicer/Slicer/tree/master/Modules/Loadable/TractographyDisplay/Widgets

**Comment by matthieuheitz** [comment]
In fact, the whole Tube tab and all its buttons affect only the Line, and never the Tube.

**Comment by matthieuheitz** [comment]
merged
