### ISSUE TITLE
Crash when saving a csv file 2 times in a row

### ISSUE THREAD

**Issue by matthieuheitz** [KitwareMedical/VesselView#92]
The problem is that the "NumberOfPoints" array is not reinitialized when running the computation a second time, so the NumberOfTuples gets false.
If a dataset has 1000 points, the first time NumberOfTuples will be equal to 1000, and the second time it will be equal to 2000.
--> Should reinitialize the array before refilling it.
The crash only appears when saving to CSV because it iterates through the array, using NumberOfTuples as the high limit, so a seg fault occurs.

**Comment by vovythevov** [comment]
Good catch !
